### ISSUE TITLE
Correct answer on quiz wrong

### ISSUE THREAD

**Issue by s33btorr** [OpenSourceEconomics/epp_topics#43]
On the script:

***Python Basics: Assignment and Built-in Scalar Types:***
 
The question that says: ***You want to convert a date that you stored as the following string "2021-01-01" to a float object. Which of the following codes do you think will do this (try on a notebook if you want)?*** and following the quiz, the correct answer is that it is possible with this code:

```python
date = "2021-01-01".replace("-", ".")
date = float(date)
``` 
But this is not correct because 2021.01.01 is not a number so it says `ValueError: could not convert string to float: '2021.01.01'`.

***"this cannot be done"*** would be the correct answer

**Comment by hmgaudecker** [comment]
Thank you!

**Comment by Marcofo21** [comment]
Thanks for the report! I opened a [PR](https://github.com/OpenSourceEconomics/epp_topics/pull/45).
